/*
 * preflight.c — screen Nektar1D inputs before spending machine time on them.
 *
 * Why
 * ---
 * A PWDB cohort is generated by sweeping haemodynamic parameters across age.
 * Push one end of the sweep too far and the other end stops being physical:
 * shrink every radius, leave the terminal resistances alone, and the thinnest
 * vessels run out of margin. A run like that costs its share of a multi-day
 * cohort before anyone sees it. Everything the failure depends on is already
 * sitting in the .in file, so it can be checked in milliseconds instead.
 *
 * What it checks, per domain, from the geometry formulas the .in carries:
 *
 *   radius > 0 over the whole domain            a taper that crosses zero is
 *                                               not a vessel
 *   initial area positive                       the IC deflates the vessel by
 *                                               the external pressure; if that
 *                                               term exceeds the wall stiffness
 *                                               the starting state is invalid
 *   CFL = dt*c/dx                               explicit time stepping needs it
 *                                               small; c comes from the same
 *                                               empirical law the model uses
 *   distance from a reference input             with --ref, how far each radius
 *                                               has drifted from a configuration
 *                                               that is known to run
 *   terminal impedance                          Z0 = rho*c/A against the
 *                                               Windkessel R. Reported, but not
 *                                               used to fail a run -- see check()
 *
 * How the radius threshold was set
 * --------------------------------
 * By experiment, not by argument. Starting from 116art_25yo.in, which runs to
 * completion, every radius was scaled by a constant with the Windkessel
 * outlets left untouched, and each result was run:
 *
 *     x0.90 x0.80 x0.78 x0.76 x0.75   run
 *     x0.74 x0.72 x0.70 x0.60 x0.50   die in the first time step, in the
 *                                     Riemann solve at a bifurcation
 *
 * So the boundary sits at about a 25% radius reduction, and it is sharp. The
 * default --rtol of 15% therefore flags earlier than strictly necessary: on
 * that sweep it calls x0.80 through x0.75 a risk although they run. That
 * asymmetry is deliberate. A false positive costs one look at a file; a false
 * negative costs a share of a multi-day cohort.
 *
 * What this is not: a physical divergence predictor. It measures distance from
 * a validated configuration. Use a reference from the same family as the files
 * being checked -- screening PWDB subjects against the solver's own demo input
 * flags all 4374 of them, because that input is a different model, not because
 * the subjects are broken.
 *
 * Build:  make preflight
 * Usage:  ./preflight sim_*.in --ref sim_1.in
 */
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MAXD 256
/* M_PI is not in ISO C; -std=c11 -pedantic hides it. */
#define PI 3.14159265358979323846

typedef struct {
    double L;                 /* domain length [m]                        */
    double r0, r1;            /* radius at x = 0 and x = L [m]            */
    double slope, icept;      /* r(x) = slope*x + icept                   */
    double k1, k2, k3;        /* wall law constants as written in the file */
    double dxmin;             /* smallest resolved spacing [m]            */
    int    terminal;          /* has a Windkessel outlet                  */
    double wr;                /* Windkessel outlet resistance             */
} Dm;

typedef struct {
    double dt, nsteps, rho, pext;
    int    ndom;
    Dm     d[MAXD];
} In;

/* c0 = sqrt( (2/3) * (Eh/D0) / rho ), Eh/D0 = k1*exp(k2*r_cm) + k3, cgs.
 * Same relation the PWDB pre-processing uses, so the numbers are comparable
 * with the PWV it reports. */
static double wave_speed(double r_m, double k1, double k2, double k3,
                         double rho_si)
{
    double r_cm  = 100.0 * r_m;
    double eh_d0 = k1 * exp(k2 * r_cm) + k3;      /* g/s^2/cm */
    return sqrt((2.0/3.0) * eh_d0 / (rho_si / 1000.0)) / 100.0;   /* m/s */
}

/* "Eh = 0.1*(3000000*exp(-13.5*100*(...)) +492963.4688)*(...)"
 *
 * Nothing is written through the out pointers until the whole line has
 * parsed. A half-filled wall law that the caller then ignores is worse than
 * no wall law: the checker would compute a wave speed from it and report OK. */
static int parse_eh(const char *s, double *k1, double *k2, double *k3)
{
    const char *p = strstr(s, "0.1*(");
    char *e;
    double a, b, c;
    if (!p) return 0;
    a = strtod(p + 5, &e);
    p = strstr(s, "exp(");
    if (!p) return 0;
    b = strtod(p + 4, &e);
    p = strstr(e, ") +");                          /* the +k3 term */
    if (!p) p = strstr(e, ")+");
    if (!p) return 0;
    c = strtod(p + 2, &e);
    if (!(a > 0) || !(c > 0)) return 0;
    *k1 = a; *k2 = b; *k3 = c;
    return 1;
}

/* "Area = PI* (-0.0049*x+0.001347) * (...)"
 *
 * The sign search is bounded by the closing parenthesis of the FIRST factor.
 * Scanning the whole line instead finds the '+' in a later factor when the
 * first one has none -- which is exactly the case a negative intercept
 * produces, "(-0.0033667*x-0.018206)*(1.0+0.5)". That returned icept = 0.5,
 * a half-metre radius, which then passes every check: rmin > 0, and
 * exp(k2*100*0.5) underflows so the wave speed and the CFL both look fine.
 * A file whose radius formula crosses zero was cleared to run. */
static int parse_area(const char *s, double *slope, double *icept)
{
    const char *p = strchr(s, '(');
    const char *close;
    char *e;
    double sl, ic;
    if (!p) return 0;
    close = strchr(p, ')');
    if (!close) return 0;
    sl = strtod(p + 1, &e);
    if (e == p + 1) return 0;
    p = strchr(e, '+');
    if (!p || p > close) { p = strchr(e, '-'); if (!p || p > close) return 0; }
    ic = strtod(p, &e);
    if (!(ic > 0)) return 0;                       /* radius at x=0 */
    *slope = sl; *icept = ic;
    return 1;
}

static int read_in(const char *path, In *in)
{
    FILE *f = fopen(path, "r");
    char line[4096], name[64];
    int cur = 0, sec = 0, bcdom = 0, bcline = 0;
    double v;
    if (!f) return 0;
    memset(in, 0, sizeof *in);
    in->dt = 1e-5; in->rho = 1060; in->pext = 0; in->nsteps = 0;

    while (fgets(line, sizeof line, f)) {
        char *p;
        if (sec == 0) {
            if (sscanf(line, "%lf %63s", &v, name) == 2) {
                if (!strcmp(name, "DT"))     in->dt     = v;
                if (!strcmp(name, "NSTEPS")) in->nsteps = v;
                if (!strcmp(name, "Rho"))    in->rho    = v;
                if (!strcmp(name, "Pext"))   in->pext   = v;
            }
        }
        if ((p = strstr(line, "Ndomains")) && (p = strchr(p, '='))) {
            in->ndom = atoi(p + 1);
            if (in->ndom < 1) { fclose(f); return 0; }      /* not a mesh file */
            if (in->ndom > MAXD) {
                fprintf(stderr, "preflight: %s declares %d domains, only the "
                        "first %d are checked\n", path, in->ndom, MAXD);
                in->ndom = MAXD;
            }
            sec = 1;
            continue;
        }
        if (!strncmp(line, "Boundary conditions", 19)) { sec = 2; bcdom = 0; bcline = 0; continue; }
        if (!strncmp(line, "Initial condition", 17))   { sec = 3; continue; }

        if (sec == 1) {
            double a, b;
            int pp, qq;
            if (strstr(line, "nel domain")) {
                int d;
                if (sscanf(strstr(line, "nel domain") + 10, "%d", &d) == 1 &&
                    d >= 1 && d <= in->ndom) cur = d;
                continue;
            }
            if (!cur) continue;
            if (sscanf(line, "%lf %lf %d %d", &a, &b, &pp, &qq) == 4 &&
                strstr(line, "x_prox")) {
                Dm *m = &in->d[cur-1];
                double dx;
                if (b > m->L) m->L = b;
                dx = (b - a) / (double)(pp > 0 && pp < 1000 ? pp * pp : 1);
                /* A zero-length element would set dxmin to 0 and, because the
                 * CFL is then computed as 0, quietly switch the CFL check off
                 * for this whole domain. Take only positive spacings, and let
                 * a domain with none fall into the unparsed bucket, which is
                 * reported rather than passed. */
                if (dx > 0 && (m->dxmin <= 0 || dx < m->dxmin)) m->dxmin = dx;
                continue;
            }
            if (!strncmp(line, "Area", 4))
                parse_area(line, &in->d[cur-1].slope, &in->d[cur-1].icept);
            else if (!strncmp(line, "Eh", 2))
                parse_eh(line, &in->d[cur-1].k1, &in->d[cur-1].k2, &in->d[cur-1].k3);
            continue;
        }

        if (sec == 2) {                       /* four lines per domain */
            if (bcdom < in->ndom) {
                if (bcline >= 2 && line[0] == 'W') {     /* distal Windkessel */
                    double w = strtod(line + 1, NULL);
                    Dm *m = &in->d[bcdom];
                    m->terminal = 1;
                    /* line 2 is the compliance, line 3 the resistance;
                     * only the resistance is used, for the impedance check */
                    if (bcline != 2) m->wr = w;
                }
                if (++bcline == 4) { bcline = 0; bcdom++; }
            }
            continue;
        }
    }
    fclose(f);

    for (cur = 0; cur < in->ndom; cur++) {
        Dm *m = &in->d[cur];
        m->r0 = m->icept;
        m->r1 = m->slope * m->L + m->icept;
    }
    return in->ndom;
}

/* ------------------------------------------------------------------ checks */

typedef struct {
    int  fatal, risk, warn, unparsed;
    char worst[160];
    double cfl;               /* worst Courant number over the domains  */
    double z;                 /* worst outlet R / characteristic Z0     */
} Report;

static void check(const In *in, const In *ref, Report *rp,
                  double zlim, double cfllim, double rtol)
{
    int i;
    double worst_cfl = 0, worst_rratio = 1, worst_z = 0;
    int    dom_cfl = 0, dom_r = 0, dom_z = 0;

    memset(rp, 0, sizeof *rp);
    rp->worst[0] = 0;

    for (i = 0; i < in->ndom; i++) {
        const Dm *m = &in->d[i];
        double rmin = m->r0 < m->r1 ? m->r0 : m->r1;
        double c1, eh, brk, cfl;

        /* A domain whose geometry did not parse has not been checked, and
         * "not checked" must never be reported as "fine". */
        /* dxmin belongs in this test too. Without it a domain with a
         * degenerate element keeps dxmin == 0, the CFL is computed as 0, and
         * the check is silently switched off for that domain while the file
         * still reports OK -- the exact outcome the dx > 0 guard upstream was
         * meant to prevent. It stopped dxmin being poisoned, not absent. */
        if (m->L <= 0 || m->icept <= 0 || m->k1 <= 0 || m->dxmin <= 0) {
            rp->unparsed++; continue;
        }

        if (rmin <= 0) {
            rp->fatal++;
            if (!rp->worst[0])
                snprintf(rp->worst, sizeof rp->worst,
                         "domain %d: radius crosses zero (%.5f -> %.5f m)",
                         i + 1, m->r0, m->r1);
            continue;
        }

        /* initial condition: A = A0 * (1 - 3/4 * r * Pext / Eh)^2 */
        eh  = 0.1 * (m->k1 * exp(m->k2 * 100.0 * rmin) + m->k3) * rmin;
        brk = 1.0 - 0.75 * rmin * in->pext / (eh > 0 ? eh : 1);
        if (brk <= 0.05) {
            rp->fatal++;
            if (!rp->worst[0])
                snprintf(rp->worst, sizeof rp->worst,
                         "domain %d: external pressure deflates the initial area "
                         "to %.3f of nominal", i + 1, brk);
            continue;
        }

        c1  = wave_speed(rmin, m->k1, m->k2, m->k3, in->rho);
        cfl = (m->dxmin > 0) ? in->dt * c1 / m->dxmin : 0;
        if (cfl > worst_cfl) { worst_cfl = cfl; dom_cfl = i + 1; }

        if (ref && i < ref->ndom && ref->d[i].icept > 0) {
            double rr = m->icept / ref->d[i].icept;
            if (fabs(log(rr)) > log(rtol)) rp->warn++;   /* count, not just worst */
            if (fabs(log(rr)) > fabs(log(worst_rratio))) {
                worst_rratio = rr; dom_r = i + 1;
            }
        }
        if (m->terminal && m->wr > 0) {
            /* Characteristic impedance of the vessel against the resistance
             * the Windkessel presents. The wave reflects at the outlet by
             * (R-Z0)/(R+Z0); as R/Z0 grows the outlet approaches a closed end. */
            double a  = PI * m->r1 * m->r1;
            double z0 = in->rho * c1 / (a > 0 ? a : 1);
            double q  = m->wr / z0;
            if (q > worst_z) { worst_z = q; dom_z = i + 1; }
        }
    }

    if (rp->unparsed) {
        rp->risk++;
        if (!rp->worst[0])
            snprintf(rp->worst, sizeof rp->worst,
                     "%d/%d domains could not be parsed - NOT checked",
                     rp->unparsed, in->ndom);
    }
    /* Reported always, but off by default, because the evidence says it does
     * not separate good inputs from bad ones:
     *
     *   116art_25yo.in   runs to completion   worst R/Z0 = 25
     *   116art_65yo.in   runs to completion   worst R/Z0 = 19
     *   the 4374 PWDB inputs                  worst R/Z0 = 4 .. 21
     *   radius x0.70 (dies in seconds)        worst R/Z0 = 14
     *
     * The highest value measured anywhere belongs to an input that runs, and
     * the input that reliably dies is mid-range. A threshold here would fail
     * a working configuration and pass a broken one. The number stays in the
     * -v output because it is informative about the model; --zlim turns it
     * into a criterion for anyone with evidence to set one. */
    if (zlim > 0 && worst_z > zlim) {
        rp->risk++;
        if (!rp->worst[0])
            snprintf(rp->worst, sizeof rp->worst,
                     "domain %d: outlet R is %.0fx the vessel impedance "
                     "(reflection %.2f) - nearly a closed end",
                     dom_z, worst_z, (worst_z - 1) / (worst_z + 1));
    }
    if (worst_cfl > cfllim) {
        rp->risk++;
        if (!rp->worst[0])
            snprintf(rp->worst, sizeof rp->worst,
                     "domain %d: CFL %.2f at dt=%.1e - explicit stepping needs < %.2f",
                     dom_cfl, worst_cfl, in->dt, cfllim);
    }
    if (ref && fabs(log(worst_rratio)) > log(rtol)) {
        rp->risk++;
        if (!rp->worst[0])
            snprintf(rp->worst, sizeof rp->worst,
                     "%d/%d domains off reference; worst is %d at %.0f%% radius "
                     "(%.0f%% area, ~%.1fx velocity for the same outlet R)",
                     rp->warn, in->ndom, dom_r, worst_rratio * 100.0,
                     worst_rratio * worst_rratio * 100.0,
                     1.0 / (worst_rratio * worst_rratio));
    }
    rp->cfl = worst_cfl;
    rp->z   = worst_z;
}

static void usage(const char *p)
{
    fprintf(stderr,
"preflight - screen Nektar1D .in files before running them\n"
"\n"
"usage: %s <file.in> [more.in ...] [--ref good.in] [-v]\n"
"  --ref <file.in>   compare against an input that is known to run. Use one\n"
"                    from the same family as the files being checked: comparing\n"
"                    a cohort against an unrelated model flags all of it. The\n"
"                    reference is skipped if it also appears in the list\n"
"  --zlim <x>        flag an outlet whose Windkessel R exceeds x times the\n"
"                    vessel impedance. Off by default: the ratio is always\n"
"                    reported, but no value of x separates the inputs that\n"
"                    run from the ones that do not, so nothing is failed on\n"
"                    it unless you have evidence for a threshold\n"
"  --cfl <x>         flag a domain whose Courant number exceeds x (default 0.40)\n"
"  --rtol <pct>      with --ref, how far a radius may differ before the input\n"
"                    is flagged (default 15). The test is on the log of the\n"
"                    ratio, so it is symmetric in ratio and not in percent:\n"
"                    15 flags a radius 13.0 pct smaller, or 15 pct larger.\n"
"                    Deliberately tighter than the measured failure boundary\n"
"                    at 25 pct: see README\n"
"  -v                also print the inputs that pass\n"
"\n"
"exit 0 all clear, 1 at least one input flagged or nothing to check\n", p);
}

int main(int argc, char **argv)
{
    static In in, ref;
    const char *refpath = NULL;
    int i, files = 0, bad = 0, verbose = 0;
    double zlim = 0.0, cfllim = 0.40, rtol_pct = 15.0;  /* zlim off: see check() */

    for (i = 1; i < argc; i++)
        if (!strcmp(argv[i], "--ref") && i + 1 < argc) refpath = argv[++i];
        else if (!strcmp(argv[i], "--zlim") && i + 1 < argc) zlim = atof(argv[++i]);
        else if (!strcmp(argv[i], "--cfl")  && i + 1 < argc) cfllim = atof(argv[++i]);
        else if (!strcmp(argv[i], "--rtol") && i + 1 < argc) rtol_pct = atof(argv[++i]);
        else if (!strcmp(argv[i], "-v")) verbose = 1;

    if (argc < 2) { usage(argv[0]); return 1; }
    if (refpath) {
        int usable = 0, k;
        if (!read_in(refpath, &ref)) {
            fprintf(stderr, "preflight: cannot read reference %s\n", refpath);
            return 1;
        }
        /* read_in() succeeds as soon as it finds an Ndomains line -- it says
         * nothing about whether any geometry parsed. A reference whose Area
         * formulas are all in a shape parse_area rejects leaves every icept at
         * zero, the per-domain comparison below is skipped for all of them,
         * and the run reports a clean sweep having compared nothing. Refuse
         * instead: "not checked" must not read as "fine", and that applies to
         * the reference as much as to the inputs. */
        for (k = 0; k < ref.ndom; k++) if (ref.d[k].icept > 0) usable++;
        if (usable == 0) {
            fprintf(stderr, "preflight: reference %s has no parseable geometry "
                    "- the --ref comparison would silently check nothing\n",
                    refpath);
            return 1;
        }
        if (usable < ref.ndom)
            fprintf(stderr, "preflight: reference %s: only %d of %d domains "
                    "parsed; the rest are not compared\n",
                    refpath, usable, ref.ndom);
    }

    for (i = 1; i < argc; i++) {
        Report rp;
        const char *p;
        if (argv[i][0] == '-') {
            if (!strcmp(argv[i], "--ref") || !strcmp(argv[i], "--zlim") ||
                !strcmp(argv[i], "--cfl") || !strcmp(argv[i], "--rtol")) i++;
            continue;
        }
        if (refpath && !strcmp(argv[i], refpath)) continue;
        if (!read_in(argv[i], &in)) { printf("%-28s  UNREADABLE\n", argv[i]); bad++; continue; }
        check(&in, refpath ? &ref : NULL, &rp, zlim, cfllim, 1.0 + rtol_pct / 100.0);
        files++;
        p = strrchr(argv[i], '/');
        p = p ? p + 1 : argv[i];
        if (rp.fatal)      { printf("%-28s  \033[1;31mFATAL\033[0m  %s\n", p, rp.worst); bad++; }
        else if (rp.risk)  { printf("%-28s  \033[1;33mRISK \033[0m  %s\n", p, rp.worst); bad++; }
        else if (verbose)  { printf("%-28s  \033[32mOK   \033[0m  %d domains, "
                                    "worst CFL %.3f, worst R/Z0 %.0f\n",
                                    p, in.ndom, rp.cfl, rp.z); }
    }
    if (files == 0) {
        /* A glob that matched nothing must not read as "everything passed". */
        fprintf(stderr, "preflight: no input files given\n");
        usage(argv[0]);
        return 1;
    }
    if (!verbose) printf("\n%d file(s) checked, %d flagged\n", files, bad);
    return bad ? 1 : 0;
}
